### ISSUE TITLE
CSS 常用布局

### ISSUE THREAD

**Issue by juzhiyuan** [juzhiyuan/Segment#35]
https://segmentfault.com/a/1190000008789039

**Comment by juzhiyuan** [comment]
### 一、常用居中方法
居中在布局中常见，假设 DOM 文档结构如下，子元素要在父元素中居中：
```html
<div class="parent">
 <div class="child"></div>
</div>
```

#### 水平居中
子元素为行内元素或块状元素、宽度是否一定，采取的布局方案不同，下面进行分析：
- 行内元素：对父元素设置 ```text-align: center;```
- 定宽块状元素：设置左右```margin``` 值为 ```auto```
- 不定宽块状元素：设置子元素为```display: inline;```，然后设置父元素为```text-align:center;```
- [通用方案：flex布局](https://github.com/juzhiyuan/Segment/issues/9#issuecomment-398776038)

**Comment by juzhiyuan** [comment]
### 二、单列布局
![image](https://user-images.githubusercontent.com/2106987/42411185-d5027bee-81f7-11e8-8794-594f103cfff8.png)

特征：定宽、水平居中

常见单列布局有两种：
1. ```header```、```content```、```footer```宽度相同，其一般不会占满浏览器最宽宽度，但当浏览器宽度缩小低于其最大宽度时，宽度会自适应
2. ```header```、```footer```宽度为浏览器宽度，但```content```不会占满浏览器宽度

对于第一种，通过对```header```、```content```、```footer```设置统一的```width```或```max-width```、并设置```margin: auto;```实现居中
```html
<div class="layout">
  <div id="header">头部</div>
  <div id="content">内容</div>
  <div id="footer">尾部</div>
</div>

  .layout{
  /*   width: 960px; *//*设置width当浏览器窗口宽度小于960px时，单列布局不会自适应。*/
    max-width: 960px;
    margin: 0 auto;
  }
```

对于第二种，```heade```r、```footer```的内容宽度为100%，但```header```、```footer```的内容区以及```content```统一设置```max-width```，并通过```margin: auto```实现居中
```html
<div id="header">
  <div class="layout">头部</div>
</div>
<div id="content" class="layout">内容</div>
<div id="footer">
  <div class="layout">尾部</div>
</div>

  .layout{
  /*   width: 960px; *//*设置width当浏览器窗口宽度小于960px时，单列布局不会自适应。*/
    max-width: 960px;
    margin: 0 auto;
  }
```

**Comment by juzhiyuan** [comment]
#### 二、position + margin
通过绝对定位，将两个侧栏固定，同样通过外边距给两个侧栏腾出空间，中间列自适应
```html
<div class="sub">left</div>
<div class="main">main</div>
<div class="extra">right</div>
```
1. 对两边侧栏分别设置宽度，设置定位方式为绝对定位
2. 设置两侧栏的 ```top: 0;```，设置左侧栏```left: 0```、右侧栏```right: 0;```
3. 对主面板设置左右外边距，```margin-left``` 值为左侧栏宽度；```margin-right```值为右侧栏宽度

```css
.sub, .extra {
  position: absolute;
  top: 0;
  width: 200px;
}

.sub {
  left: 0;
}

.extra {
  right: 0;
}

.main {
  margin: 0 200px;
}
```

- 与上一种方法相比，本方法是通过定位来实现侧栏的位置固定
- 如果中间栏含有最小宽度限制，或是含有宽度的内部元素，则浏览器窗口小到一定程度，主面板与侧栏会发生重叠
- 如果是左边带有侧栏的二栏布局，则去掉右侧栏，不要设置主面板的```margin-right```值，其他操作相同。反之亦然

**Comment by juzhiyuan** [comment]
### 三、圣杯布局（float + -margin + padding + position）
主面板设置宽度为100%，主面板与两个侧栏都设置浮动，常见为左浮动。这时两个侧栏会被主面板挤压下去，通过负边距将浮动的侧栏拉上来，左侧栏的负边距为100%，刚好是窗口的宽度，因此会从主面板下面的左边跑到与主面板对齐的左边、右侧栏此时浮动在主面板下面的左边，设置负边距为负的自身宽度刚好浮动为左右侧栏的宽度，给侧栏腾出空间，此时主面板宽度减小

由于侧栏的负margin 都是相对主面板的，两个侧栏并不会停靠在左右两边，而是跟着缩小的主面板一起向中间靠拢，此时使用相对布局，调整两个侧栏到相应位置

```html
 <div id="bd">         
    <div class="main"></div>        
    <div class="sub"></div>        
    <div class="extra"></div>  
</div> 
```

1. 三者都设置浮动
2. 设置 main 宽度为100%，设置两侧栏宽度
3. 设置 负边距，sub 设置负边距为100%，extra 设置负边距为负的自身宽度
4. 设置 main 的 padding 值给左右两个子面板留出空间
5. 设置两个子面板为相对定位，sub 的 left值为负的 sub 宽度；extra 的 right 值为 负的 extra 宽度

```css
.main {        
    float: left;       
    width: 100%;   
 }  
 .sub {       
    float: left;        
    width: 190px;        
    margin-left: -100%;               
    position: relative;  
    left: -190px;  
}   
.extra {        
    float: left;        
    width: 230px;        
    margin-left: -230px; 
    position: relative; 
    right: -230px;  
 }
#bd {        
    padding: 0 230px 0 190px;   
 }
```

注意：
- DOM 元素书写顺序不得改变
- 当面板的 main 内容部分比两边的子面板宽度小的时候，布局就会乱掉。可以通过设置 main 的 min-width属性或使用双飞翼布局避免问题。

**Comment by juzhiyuan** [comment]
#### 四、双飞翼布局(float + 负margin + margin)
双飞翼布局和圣杯布局的思想有些相似，都利用了浮动和负边距，但双飞翼布局在圣杯布局上做了改进，在main元素上加了一层div, 并设置margin,由于两侧栏的负边距都是相对于main-wrap而言，main的margin值变化便不会影响两个侧栏，因此省掉了对两侧栏设置相对布局的步骤

```html
<div id="main-wrap" class="column">
      <div id="main">#main</div>
</div>
<div class="sub"></div>        
<div class="extra"></div>
```

1. 三者都设置向左浮动
2. 设置main-wrap宽度为100%，设置两个侧栏的宽度
3. 设置 负边距，sub设置负左边距为100%，extra设置负左边距为负的自身宽度
4. 设置main的margin值给左右两个子面板留出空间

```css
.main-wrap {        
    float: left;       
    width: 100%;   
 }  
 .sub {       
    float: left;        
    width: 190px;        
    margin-left: -100%;   
}   
.extra {        
    float: left;        
    width: 230px;        
    margin-left: -230px; 
 }
.main {    
    margin: 0 230px 0 190px;
}
```
注意：
- 圣杯采用的是padding，而双飞翼采用的margin，解决了圣杯布局main的最小宽度不能小于左侧栏的缺点
- 双飞翼布局不用设置相对布局，以及对应的left和right值
- 通过引入相对布局，可以实现三栏布局的各种组合，例如对右侧栏设置position: relative; left: 190px; ,可以实现sub+extra+main的布局
- 如果是左边带有侧栏的二栏布局，则去掉右侧栏，不要设置main-wrap的margin-right值，其他操作相同。反之亦然
